Error: execution error at (sscs-ccd-definitions/charts/nodejs/charts/library/templates/v2/_deployment.tpl:15:3): An image must be supplied to the chart (#744)
08:36:52  Release sscs-ccd-definitions-staging does not exist. Installing it now.
08:36:52  [Pipeline] }